# 服务配置
server:
  # 服务端口
  port: 80
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat 的URI编码
    uri-encoding: UTF-8
    # tomcat 最大线程数,默认为200
    max-threads: 800
    # tomcat 启动初始化的线程数，默认值10
    min-spare-threads: 30

spring:
  profiles:
    # 环境 dev|test|prod
    active: dev
  mvc:
    # 出现404错误时，直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    # 是否开启默认的资源处理，默认为true
    add-mappings: false

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ritian.modules.*.entity